<?php
define ("DB_ERROR","ERROR DESCONOCIDO");
define ("DB_ERROR_ALREADY_EXISTS","YA EXISTE");
define ("DB_ERROR_CANNOT_CREATE","NO SE PUEDE CREAR");
define ("DB_ERROR_CANNOT_MODIFI","NO SE PUEDE ACTUALIZAR");
define ("DB_ERROR_CANNOT_DELETE","NO SE PUEDE BORRAR");
define ("DB_ERROR_CONSTRAINT","VIOLACION DE INTEGRIDAD");
define ("DB_ERROR_DIVZERO","DIVISION PARA CERO");
define ("DB_ERROR_INVALID ","INVALIDO");
define ("DB_ERROR_INVALID_DATE","FECHA INVALIDA");
define ("DB_ERROR_INVALID_NUMBER ","NUMERO INVALIDO");
define ("DB_ERROR_MISMATCH","ERROR EN EL TIPO DE DATO");
define ("DB_ERROR_NODBSELECTED","BASE DE DATOS NO SELECCIONADA");
define ("DB_ERROR_NOSUCHFIELD","NO EXISTE EL CAMPO");
define ("DB_ERROR_NOSUCHTABLE","NO EXISTE LA TABLA");
define ("DB_ERROR_NOT_FOUND","NO ENCONTRADO");
define ("DB_ERROR_LOCKED","BLOQUEADO");
define ("DB_ERROR_SYNTAX","ERROR DE SINTAXIS");
define ("DB_ERROR_UNSUPPORTED","NO SOPORTADO");
define ("DB_ERROR_VALUE_COUNT_ON_ROW","ERROR DE VALOR EN REGISTRO");
define ("DB_ERROR_NOT_FIND_RECORD","NO SE ENCONTRARON REGISTROS");
define ("DB_ERROR_INVALID_DSN","DNS INVALIDO");
define ("DB_ERROR_CONNECT_FAILED","CONEXION FALLIDA");
define ("DB_OK","OK");
define ("DB_ERROR_NEED_MORE_DATA","INSUFICIENTES DATOS");
define ("DB_ERROR_ACCESS_VIOLATION","PERMISOS INSUFICIENTES");
?>